---
- hosts: overcloud
  vars:
    metadata:
      name: Hardware Discovery
      description: Validations that run after the hardware was discovered.
      stage: discovery
- include: ../validations/dummy_a.yaml
- include: ../validations/dummy_b.yaml
