---
- hosts: controller
  vars:
    metadata:
      name: Neutron Sanity Check
      description: >
        Run `neutron-sanity-check` to find out potential issues with
        Neutron's configuration.
  tasks:
  - name: Run neutron-sanity-check
    command: neutron-sanity-check --config-file /etc/neutron/neutron.conf
